# This is a basic workflow to help you get started with Actions

name: Canary-strategy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployapp:
    # The type of runner that the job will run on
    permissions:
      id-token: write
      contents: read
      
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GKE_PROVIDER_ID }}
          service_account: ${{ secrets.GKE_SERVICE_ACCOUNT }}
          audience: 'https://github.com/Strikers14/nginx-test'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Install Google Cloud Auth plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Get Kubernetes config
        run: gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --zone asia-northeast3-a --project ${{ secrets.PROJECT_ID }}

      - name: "Deploy v1"
        run: |
          kubectl apply -f ./canary/deployment-old.yaml

      - name: "expose v1"
        run: |
          kubectl apply -f ./canary/gateway.yaml -f canary/virtualservice.yaml

      - name: "Check v1 status"
        run: |
          kubectl rollout status deploy app-01 -w
  
      - name: "Deploy v2"
        run: |
          kubectl apply -f ./canary/deployment-new.yaml
      
      - name: "Check v2 staus"
        run: |
          kubectl rollout status deploy app-02 -w

      - name: "Traffic Split"
        run: |
          kubectl apply -f ./canary/destinationrule.yaml -f ./canary/virtualservice-split.yaml
      
